### ISSUE TITLE
Italmed players do not get faces

### ISSUE THREAD

**Issue by nevemlaci** [brettfarrow/newgan-validator#1]
Italmed players do not get faces as the game is case sensitive when it loads images. For example
_Italmed3205_ image is _ItalMed3205_ in the facepack so the game does not properly load it.

**Comment by brettfarrow** [comment]
Does this happen on Windows, Mac, or both?

**Comment by nevemlaci** [comment]
windows

**Comment by brettfarrow** [comment]
This should be fixed now: https://github.com/brettfarrow/newgan-validator/commit/ef9046c4866c18559ccb1a93091166d002782fbf
